import type { ResumeTemplate } from './types'

export const classic: ResumeTemplate = {
  id: 'classic',
  name: 'Classic',
  description: 'Editorial serif display with clean sans body. The original.',
  htmlTokens: {
    fontDisplay: '"Source Serif 4", "Source Serif Pro", Georgia, "Times New Roman", serif',
    fontBody: '"Inter", "Helvetica Neue", Helvetica, Arial, sans-serif',
    colorInk: '#111111',
    colorMuted: '#5e5e5e',
    colorRule: '#d9d9d9',
    colorPage: '#ffffff',
    nameSizePt: 30,
    titleSizePt: 12,
    sectionHeadingSizePt: 14,
    bodySizePt: 10.5,
    metaSizePt: 10,
    contactSizePt: 9,
    baseLineHeight: 1.5,
    bulletGlyph: '•',
    showSectionRule: true,
    sectionHeaderCase: 'normal',
    accentColor: null,
    accentRole: 'none',
  },
  pdfTokens: {
    fontDisplay: 'Source Serif 4',
    fontBody: 'Inter',
    colorInk: '#111111',
    colorMuted: '#5e5e5e',
    colorRule: '#d9d9d9',
    colorPage: '#ffffff',
    nameSize: 26,
    titleSize: 12,
    sectionHeadingSize: 13,
    bodySize: 10.5,
    metaSize: 10,
    contactSize: 9,
    pageMarginX: 43.2,
    pageMarginY: 39.6,
    sectionTop: 16,
    sectionHeadingBottom: 6,
    entryGap: 9,
    bulletIndent: 8,
    lineHeightBody: 1.4,
    lineHeightHeading: 1.1,
    bulletGlyph: '•',
    showSectionRule: true,
    sectionHeaderCase: 'normal',
    accentColor: null,
    accentRole: 'none',
  },
}
