import type { ResumeTemplate } from './types'

export const minimal: ResumeTemplate = {
  id: 'minimal',
  name: 'Minimal',
  description: 'Restrained all-sans with light weights and generous whitespace. Editorial calm.',
  htmlTokens: {
    fontDisplay: '"Inter", "Helvetica Neue", Helvetica, Arial, sans-serif',
    fontBody: '"Inter", "Helvetica Neue", Helvetica, Arial, sans-serif',
    colorInk: '#1a1a1a',
    colorMuted: '#7a7a7a',
    colorRule: '#e8e8e8',
    colorPage: '#ffffff',
    nameSizePt: 20,
    titleSizePt: 10.5,
    sectionHeadingSizePt: 9,
    bodySizePt: 10,
    metaSizePt: 9.5,
    contactSizePt: 8.75,
    baseLineHeight: 1.65,
    bulletGlyph: '·',
    showSectionRule: false,
    sectionHeaderCase: 'upper',
    accentColor: null,
    accentRole: 'none',
    nameWeight: 600,
    bodyWeight: 400,
    sectionHeadingWeight: 600,
    nameLetterSpacingEm: -0.005,
    sectionHeadingLetterSpacingEm: 0.22,
    sectionTopPx: 28,
    sectionHeadingBottomPx: 10,
    entryGapPx: 14,
    pagePaddingXIn: 0.75,
    pagePaddingYIn: 0.7,
  },
  pdfTokens: {
    fontDisplay: 'Inter',
    fontBody: 'Inter',
    colorInk: '#1a1a1a',
    colorMuted: '#7a7a7a',
    colorRule: '#e8e8e8',
    colorPage: '#ffffff',
    nameSize: 18,
    titleSize: 10.5,
    sectionHeadingSize: 8.75,
    bodySize: 10,
    metaSize: 9.5,
    contactSize: 8.75,
    pageMarginX: 54,
    pageMarginY: 50,
    sectionTop: 22,
    sectionHeadingBottom: 8,
    entryGap: 12,
    bulletIndent: 9,
    lineHeightBody: 1.55,
    lineHeightHeading: 1.15,
    bulletGlyph: '·',
    showSectionRule: false,
    sectionHeaderCase: 'upper',
    accentColor: null,
    accentRole: 'none',
    nameWeight: 600,
    bodyWeight: 400,
    sectionHeadingWeight: 600,
    nameLetterSpacing: 0,
    sectionHeadingLetterSpacing: 1.8,
  },
}
