import type { ResumeTemplate } from './types'

export const minimal: ResumeTemplate = {
  id: 'minimal',
  name: 'Minimal',
  description: 'Pared-back sans-serif with generous whitespace. No accent color, no rules.',
  htmlTokens: {
    fontDisplay: '"Inter", "Helvetica Neue", Helvetica, Arial, sans-serif',
    fontBody: '"Inter", "Helvetica Neue", Helvetica, Arial, sans-serif',
    colorInk: '#1f1f1f',
    colorMuted: '#6b6b6b',
    colorRule: '#ececec',
    colorPage: '#ffffff',
    nameSizePt: 26,
    titleSizePt: 12,
    sectionHeadingSizePt: 12,
    bodySizePt: 10.5,
    metaSizePt: 10,
    contactSizePt: 9,
    baseLineHeight: 1.55,
    bulletGlyph: '•',
    showSectionRule: false,
    sectionHeaderCase: 'normal',
    accentColor: null,
    accentRole: 'none',
  },
  pdfTokens: {
    fontDisplay: 'Inter',
    fontBody: 'Inter',
    colorInk: '#1f1f1f',
    colorMuted: '#6b6b6b',
    colorRule: '#ececec',
    colorPage: '#ffffff',
    nameSize: 22,
    titleSize: 12,
    sectionHeadingSize: 12,
    bodySize: 10.5,
    metaSize: 10,
    contactSize: 9,
    pageMarginX: 50,
    pageMarginY: 50,
    sectionTop: 18,
    sectionHeadingBottom: 6,
    entryGap: 10,
    bulletIndent: 8,
    lineHeightBody: 1.5,
    lineHeightHeading: 1.1,
    bulletGlyph: '•',
    showSectionRule: false,
    sectionHeaderCase: 'normal',
    accentColor: null,
    accentRole: 'none',
  },
}
