import type { ResumeTemplate } from './types'

// Deep graphite-indigo. Reads as confident and editorial — not a "branded"
// teal. Used sparingly on section headers; name stays in ink for weight.
const ACCENT = '#1f2a44'

export const modern: ResumeTemplate = {
  id: 'modern',
  name: 'Modern',
  description: 'Editorial serif display paired with tracked uppercase sans headers. Contemporary and confident.',
  htmlTokens: {
    fontDisplay: '"Source Serif 4", "Source Serif Pro", Georgia, "Times New Roman", serif',
    fontBody: '"Inter", "Helvetica Neue", Helvetica, Arial, sans-serif',
    colorInk: '#0e1116',
    colorMuted: '#5b6470',
    colorRule: '#1f2a44',
    colorPage: '#ffffff',
    nameSizePt: 32,
    titleSizePt: 11,
    sectionHeadingSizePt: 9.5,
    bodySizePt: 10.25,
    metaSizePt: 9.75,
    contactSizePt: 9,
    baseLineHeight: 1.45,
    bulletGlyph: '–',
    showSectionRule: false,
    sectionHeaderCase: 'upper',
    accentColor: ACCENT,
    accentRole: 'sectionHeaders',
    nameWeight: 400,
    bodyWeight: 400,
    sectionHeadingWeight: 700,
    nameLetterSpacingEm: -0.025,
    sectionHeadingLetterSpacingEm: 0.18,
    sectionTopPx: 20,
    sectionHeadingBottomPx: 6,
    entryGapPx: 11,
    pagePaddingXIn: 0.6,
    pagePaddingYIn: 0.55,
  },
  pdfTokens: {
    fontDisplay: 'Source Serif 4',
    fontBody: 'Inter',
    colorInk: '#0e1116',
    colorMuted: '#5b6470',
    colorRule: '#1f2a44',
    colorPage: '#ffffff',
    nameSize: 28,
    titleSize: 11,
    sectionHeadingSize: 9.25,
    bodySize: 10.25,
    metaSize: 9.75,
    contactSize: 9,
    pageMarginX: 43.2,
    pageMarginY: 39.6,
    sectionTop: 14,
    sectionHeadingBottom: 5,
    entryGap: 9,
    bulletIndent: 8,
    lineHeightBody: 1.42,
    lineHeightHeading: 1.05,
    bulletGlyph: '–',
    showSectionRule: false,
    sectionHeaderCase: 'upper',
    accentColor: ACCENT,
    accentRole: 'sectionHeaders',
    nameWeight: 400,
    bodyWeight: 400,
    sectionHeadingWeight: 700,
    nameLetterSpacing: -0.7,
    sectionHeadingLetterSpacing: 1.6,
  },
}
