import type { ResumeTemplate } from './types'

const ACCENT = '#0d6e6e'

export const modern: ResumeTemplate = {
  id: 'modern',
  name: 'Modern',
  description: 'All-sans typography with a teal accent on your name and section headers.',
  htmlTokens: {
    fontDisplay: '"Inter", "Helvetica Neue", Helvetica, Arial, sans-serif',
    fontBody: '"Inter", "Helvetica Neue", Helvetica, Arial, sans-serif',
    colorInk: '#111111',
    colorMuted: '#5e5e5e',
    colorRule: '#e5e7eb',
    colorPage: '#ffffff',
    nameSizePt: 28,
    titleSizePt: 12,
    sectionHeadingSizePt: 11,
    bodySizePt: 10.5,
    metaSizePt: 10,
    contactSizePt: 9,
    baseLineHeight: 1.45,
    bulletGlyph: '–',
    showSectionRule: false,
    sectionHeaderCase: 'upper',
    accentColor: ACCENT,
    accentRole: 'both',
  },
  pdfTokens: {
    fontDisplay: 'Inter',
    fontBody: 'Inter',
    colorInk: '#111111',
    colorMuted: '#5e5e5e',
    colorRule: '#e5e7eb',
    colorPage: '#ffffff',
    nameSize: 24,
    titleSize: 12,
    sectionHeadingSize: 11,
    bodySize: 10.5,
    metaSize: 10,
    contactSize: 9,
    pageMarginX: 43.2,
    pageMarginY: 39.6,
    sectionTop: 14,
    sectionHeadingBottom: 5,
    entryGap: 8,
    bulletIndent: 8,
    lineHeightBody: 1.4,
    lineHeightHeading: 1.1,
    bulletGlyph: '–',
    showSectionRule: false,
    sectionHeaderCase: 'upper',
    accentColor: ACCENT,
    accentRole: 'both',
  },
}
